#!/usr/bin/env python3
"""Build "Lead the Shift" (Les Assises 2026) in two editions, each with a standalone copy.

The talk is written in assets/assises/ (deck.src.html, deck.css, deck.js, the
photos); the fonts are the same embedded subset as ai-talk.html
(assets/assises/fonts.css). Two outputs:

    assises.html                       cinematic edition, dark stage
    assises-wavestone.html             Wavestone edition: white and indigo
                                       grounds, arcs, sweeps (wavestone.css/js
                                       layered on top of the same scenes)
    *-standalone.html                  the same files with every image inlined:
                                       one file for a USB stick, no network

    python3 tools/build-assises.py
"""
import base64, mimetypes, re
from pathlib import Path

root = Path(__file__).resolve().parent.parent
src = root / 'assets/assises'
read = lambda p: (src / p).read_text(encoding='utf-8')

def build(extra_css='', extra_js='', title=None):
    page = read('deck.src.html')
    for mark, part in (('/*FONTS*/', read('fonts.css')), ('/*CSS*/', read('deck.css') + '\n' + extra_css), ('/*JS*/', read('deck.js'))):
        if page.count(mark) != 1:
            raise SystemExit(f'build-assises: expected one {mark} in deck.src.html')
        page = page.replace(mark, part.strip())
    if extra_js:
        hook = 'if (PRESENTER) presenter();\nelse {'
        if page.count(hook) != 1:
            raise SystemExit('build-assises: expected one start-up block in deck.js')
        page = page.replace(hook, extra_js.strip() + '\n\n' + hook)
    if title:
        page = page.replace('<title>Lead the Shift · Les Assises 2026</title>', f'<title>{title}</title>', 1)
    head, rest = page.split('\n', 1)
    return head + '\n<!-- Generated by tools/build-assises.py from assets/assises/: edit those, not this file. -->\n' + rest

cache = {}
def inline(m):
    p = m.group(0)
    if p not in cache:
        f = root / p
        if not f.exists():
            raise SystemExit(f'build-assises: missing {p}')
        mime = mimetypes.guess_type(f.name)[0] or 'application/octet-stream'
        cache[p] = f'data:{mime};base64,' + base64.b64encode(f.read_bytes()).decode()
    return cache[p]

for name, page in (('assises', build()),
                   ('assises-wavestone', build(read('wavestone.css'), read('wavestone.js'), 'Lead the Shift · Les Assises 2026, Wavestone edition'))):
    (root / f'{name}.html').write_text(page, encoding='utf-8')
    standalone = re.sub(r'assets/assises/[\w./-]+\.(?:jpg|png|svg)', inline, page)
    (root / f'{name}-standalone.html').write_text(standalone, encoding='utf-8')
    print(f'{name}.html ({len(page) // 1024} KB) and {name}-standalone.html ({len(standalone) // 1024} KB) written')
