#!/usr/bin/env python3
"""Build assises.html and assises-standalone.html: "Lead the Shift", Les Assises 2026.

The talk is written in assets/assises/ (deck.src.html, deck.css, deck.js, the
photos); the fonts are the same embedded subset as ai-talk.html
(assets/assises/fonts.css). Two outputs:

    assises.html             the talk, photos loaded from assets/assises/
    assises-standalone.html  the same file with every image inlined: one file
                             to copy on a USB stick, runs with no network

    python3 tools/build-assises.py
"""
import base64, mimetypes, re
from pathlib import Path

root = Path(__file__).resolve().parent.parent
src = root / 'assets/assises'
read = lambda p: (src / p).read_text(encoding='utf-8')

page = read('deck.src.html')
for mark, part in (('/*FONTS*/', read('fonts.css')), ('/*CSS*/', read('deck.css')), ('/*JS*/', read('deck.js'))):
    if page.count(mark) != 1:
        raise SystemExit(f'build-assises: expected one {mark} in deck.src.html')
    page = page.replace(mark, part.strip())
head, rest = page.split('\n', 1)
page = head + '\n<!-- Generated by tools/build-assises.py from assets/assises/ (deck.src.html, deck.css, deck.js): edit those, not this file. -->\n' + rest
(root / 'assises.html').write_text(page, encoding='utf-8')

cache = {}
def inline(m):
    p = m.group(0)
    if p not in cache:
        f = root / p
        if not f.exists():
            raise SystemExit(f'build-assises: missing {p}')
        mime = mimetypes.guess_type(f.name)[0] or 'application/octet-stream'
        cache[p] = f'data:{mime};base64,' + base64.b64encode(f.read_bytes()).decode()
    return cache[p]
used = set(re.findall(r'assets/assises/[\w./-]+\.(?:jpg|png|svg)', page))
standalone = re.sub(r'assets/assises/[\w./-]+\.(?:jpg|png|svg)', inline, page)
(root / 'assises-standalone.html').write_text(standalone, encoding='utf-8')
print(f'assises.html ({len(page) // 1024} KB) and assises-standalone.html ({len(standalone) // 1024} KB, {len(used)} images) written')
