#!/usr/bin/env python3
"""Build ai-talk-photo-sleek.html: the talk, with photos, on a cinematic dark stage.

Same content as ai-talk.html (never edited by hand): the photo set
(assets/ai/photos/photoset.js), the narration index (assets/ai/voice/narration.js,
recorded by tools/build-talk-voice.py), then the sleek layer (assets/ai/sleek/sleek.css
and sleek.js) are inlined so the page still works offline. Run it again after
any change to ai-talk.html, the photo set, the narration or the sleek layer:

    python3 tools/build-talk-sleek.py
"""
from pathlib import Path

root = Path(__file__).resolve().parent.parent
read = lambda p: (root / p).read_text(encoding='utf-8')
talk, photoset = read('ai-talk.html'), read('assets/ai/photos/photoset.js')
css, js = read('assets/ai/sleek/sleek.css'), read('assets/ai/sleek/sleek.js')
narr = read('assets/ai/voice/narration.js') if (root / 'assets/ai/voice/narration.js').exists() else ''

def swap(text, old, new):
    if text.count(old) != 1:
        raise SystemExit(f'build-talk-sleek: expected one "{old[:60]}" in ai-talk.html')
    return text.replace(old, new)

out = swap(talk, '<title>Out of the Sandbox · Talk</title>', '<title>Out of the Sandbox · Talk, sleek edition</title>')
out = swap(out, '</head>', f'<style>\n{css.strip()}\n</style>\n</head>')
out = swap(out, 'if (PRESENTER) presenter();\nelse {',
           f'// ─── Photo edition ───\n{photoset.strip()}\n\n// ─── Narration ───\n{narr.strip()}\n\n// ─── Sleek edition ───\n{js.strip()}\n\nif (PRESENTER) presenter();\nelse {{')
head, rest = out.split('\n', 1)
out = head + '\n<!-- Generated by tools/build-talk-sleek.py from ai-talk.html, assets/ai/photos/photoset.js, assets/ai/voice/narration.js and assets/ai/sleek/: edit those, not this file. -->\n' + rest
(root / 'ai-talk-photo-sleek.html').write_text(out, encoding='utf-8')
print('ai-talk-photo-sleek.html written')
