#!/usr/bin/env python3
"""Build ai-talk-photos.html: the talk (ai-talk.html) with photos.

The photo edition is not edited by hand. It is ai-talk.html plus the photo
set in assets/ai/photos/photoset.js, inlined so the page still works offline.
Run it again after any change to ai-talk.html or to the photo set:

    python3 tools/build-talk-photos.py
"""
from pathlib import Path

root = Path(__file__).resolve().parent.parent
talk = (root / 'ai-talk.html').read_text(encoding='utf-8')
photoset = (root / 'assets/ai/photos/photoset.js').read_text(encoding='utf-8')

def swap(text, old, new):
    if text.count(old) != 1:
        raise SystemExit(f'build-talk-photos: expected one "{old[:60]}" in ai-talk.html')
    return text.replace(old, new)

out = swap(talk, '<title>Out of the Sandbox · Talk</title>', '<title>Out of the Sandbox · Talk, photo edition</title>')
out = swap(out, 'if (PRESENTER) presenter();\nelse {', f'// ─── Photo edition: built from assets/ai/photos/photoset.js ───\n{photoset.strip()}\n\nif (PRESENTER) presenter();\nelse {{')
head, rest = out.split('\n', 1)
out = head + '\n<!-- Generated by tools/build-talk-photos.py from ai-talk.html and assets/ai/photos/photoset.js: edit those, not this file. -->\n' + rest
(root / 'ai-talk-photos.html').write_text(out, encoding='utf-8')
print('ai-talk-photos.html written')
